export const contactList = [
  {
    id: 1,
    name: "Catherine",
    profilePic: "/profile/user1.png",
    lastText: "Hey Man",
    lastTextTime: "12:58 ",
    status: "online",
    ShowOnline: "Off",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 2,
    name: "Moana",
    profilePic: "/profile/user2.png",
    lastText: `Yo bro I got some info `,
    lastTextTime: "12:45 ",
    status: "offline",
    ShowOnline: "Off",
    seen: "unread",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 3,
    name: "Elon Bezoz",
    profilePic: "/profile/user3.png",
    lastText: "Where is my bag?",
    lastTextTime: "12:30 ",
    status: "offline",
    ShowOnline: "Off",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 4,
    name: "Jeff Musk",
    profilePic: "/profile/user4.png",
    lastText: "Travelling to space",
    lastTextTime: "12:00 ",
    ShowOnline: "Off",
    status: "offline",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 5,
    name: "Jegaer ",
    profilePic: "/profile/user5.png",
    lastText: "All okay?",
    lastTextTime: "05:00 ",
    status: "offline",
    ShowOnline: "Off",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 6,
    name: "Nagertg",
    profilePic: "/profile/user6.png",
    lastText: "Travelling to delhi",
    lastTextTime: "08:00 ",
    ShowOnline: "Off",
    status: "offline",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 7,
    name: "rohan ",
    profilePic: "/profile/elon.jpeg",
    lastText: "Travelling to space",
    lastTextTime: "06:00 ",
    status: "offline",
    seen: "read",
    ShowOnline: "Off",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 8,
    name: "roha ",
    profilePic: "/profile/Online1.png",
    lastText: "Travelling to space",
    lastTextTime: "06:00 ",
    status: "online",
    ShowOnline: "On",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 9,
    name: "rohit ",
    profilePic: "/profile/Online2.png",
    lastText: "Travelling to space",
    lastTextTime: "06:00 ",
    ShowOnline: "On",
    status: "online",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 10,
    name: "rohan ",
    profilePic: "/profile/Online3.png",
    lastText: "Travelling to space",
    lastTextTime: "06:00 ",
    ShowOnline: "On",
    status: "online",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 11,
    name: "rohan ",
    profilePic: "/profile/Online4.png",
    lastText: "Travelling to space",
    lastTextTime: "06:00 ",
    status: "online",
    ShowOnline: "On",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
  {
    id: 12,
    name: "rohan ",
    profilePic: "/profile/Online5.png",
    lastText: "Travelling to space",
    lastTextTime: "06:00 ",
    status: "online",
    ShowOnline: "On",
    seen: "read",
    number: "+62 8224 2384",
    files: [
      {
        filename: "Citation",
        filesize: "1.2 MB",
        fileicon: "/file/Document.png",
      },
      {
        filename: "sample.png",
        filesize: "1 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample2.mp3",
        filesize: "2 MB",
        fileicon: "/file/music.png",
      },
      {
        filename: "sample3.png",
        filesize: "1.8 MB",
        fileicon: "/file/Image.png",
      },
      {
        filename: "sample4.png",
        filesize: "1.5 MB",
        fileicon: "/file/Document.png",
      },
    ],
  },
];
export const messagesList = [
  {
    id: 1,
    messageType: "TEXT",
    text: "Hey Man ",
    senderID: 1,
    addedOn: "12:00 ",
  },
  {
    id: 2,
    messageType: "IMAGE",
    image: ["/Rectangle1.png", "/Rectangle2.png"],
    senderID: 1,
    addedOn: "05:15",
  },
  {
    id: 3,
    messageType: "TEXT",
    text: "Hey, What's up? ",
    senderID: 0,
    addedOn: "12:01 ",
  },
  {
    id: 4,
    messageType: "TEXT",
    text: "All Good, What about you? ",
    senderID: 1,
    addedOn: "12:00 ",
  },
  {
    id: 5,
    messageType: "TEXT",
    text: "I'm good as well",
    senderID: 0,
    addedOn: "12:00 ",
  },
  {
    id: 6,
    messageType: "TEXT",
    text: "Great 😁",
    senderID: 1,
    addedOn: "12:00 ",
  },
  {
    id: 7,
    messageType: "TEXT",
    text: "okay ",
    senderID: 0,
    addedOn: "12:00 ",
  },
  {
    id: 8,
    messageType: "VIDEO",
    video: [],
    senderID: 1,
    addedOn: "12:00 ",
  },
];
